image: node:12.7-alpine

stages:
  - check
  - build
  - deploy

eslint:
  stage: check
  before_script:
    - yarn --silent
  script:
    - yarn lint

code-format:
  stage: check
  before_script:
    - yarn --silent
  script:
    - yarn format:check

.yarn_build:
  before_script:
    - yarn --silent
  script:
    - yarn build:${APP_ENV} --silent
  artifacts:
    paths:
      - ./build

build_dev:
  extends: .yarn_build
  stage: build
  variables:
    APP_ENV: dev
  except:
    refs:
      - master

build_prod:
  extends: .yarn_build
  stage: build
  variables:
    APP_ENV: prod
  only:
    refs:
      - master

deploy-aws:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  script:
    - ls
    - aws s3 sync ./build s3://${AWS_S3_BUCKET}
